### ISSUE TITLE
トークンの検証と更新が間違っている気がする

### ISSUE THREAD

**Issue by pddg** [jphacks/KB_1809#50]
`AuthService.kt` では下記のように定義されている

```kotlin
    @POST("/auth/jwt/refresh")
    fun refresh(@Body token: String): Call<Authorization>

    @POST("/auth/jwt/verify")
    fun verify(@Body token: String): Call<Authorization>
```

`@Body token: String`だと，普通にリクエストボディは

```
<なんか長いトークン>
```

になるように思います．実際に必要なリクエストボディは

```json
{
  "token": "<なんか長いトークン>"
}
```

というJSONになります．レスポンスのボディも同様のJSONになるので，`Token.kt`とかを作ってシリアライズ／デシリアライズする必要があるのでは？

あの書き方でJSONが生成されるなら僕の知識不足です．

**Comment by ken-kentan** [comment]
fixed in de19279
