### ISSUE TITLE
Trailing slashがない

### ISSUE THREAD

**Issue by pddg** [jphacks/KB_1809#51]
バックエンドサーバでは各エンドポイントURLの末尾にはTrailing slashが必須になっていたはずです．
同じServiceファイルの中でも表記ブレが起きているので，`/`は全てに付けておいて欲しいです．

**Comment by ken-kentan** [comment]
表記は合わせておきます。
なお、現状はTrailing slashがなくても正しく動作しているようです。（POST, GET共）
